import { ROLES } from '../../shared/constants/roles-const.js'
import { CREDENTIALS } from '../../shared/constants/credentialUser-const.js'

export const user_data = [
	{
		full_name: 'Angelo García',
		identification_card: '0000000000',
		email: CREDENTIALS.GOD_1,
		code: 'ADGA',
		roles: [ROLES.GENERAL_ADMIN, ROLES.ACCESS_MANAGER, ROLES.DIRECTOR, ROLES.SUPERVISOR, ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'Cosme Soto',
		identification_card: '0000000000',
		email: CREDENTIALS.GOD_2,
		code: 'CS',
		roles: [ROLES.GENERAL_ADMIN, ROLES.ACCESS_MANAGER, ROLES.DIRECTOR, ROLES.SUPERVISOR, ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'Favián Bayas',
		identification_card: '0000000002',
		phone: '0000000002',
		email: CREDENTIALS.FABIANB,
		code: 'FB',
		roles: [ROLES.DIRECTOR],
	},
	{
		full_name: 'Manuela Isabel Paredes Villena',
		identification_card: '0201433539',
		phone: '0996567172',
		email: CREDENTIALS.ISABELP,
		code: 'MIPV',
		roles: [ROLES.SUPERVISOR, ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'María Fernanda Quinteros Meneses',
		identification_card: '1804622247',
		phone: '0983908482',
		email: CREDENTIALS.MAFERQ,
		code: 'MFQM',
		roles: [ROLES.TECHNICAL_ANALYST, ROLES.ACCESS_MANAGER],
	},
	{
		full_name: 'Erika Carolina Cortés Rojas',
		identification_card: '0202332524',
		phone: '0995281385',
		email: CREDENTIALS.ERIKAC,
		code: 'ECCR',
		roles: [ROLES.TECHNICAL_ANALYST, ROLES.ACCESS_MANAGER],
	},
	{
		full_name: 'María Paola Wilcaso Fajardo',
		identification_card: '0201814506',
		phone: '0993690131',
		email: CREDENTIALS.PAOLAW,
		code: 'MPWF',
		roles: [ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'Santiago Xavier Santos Jara',
		identification_card: '0202285953',
		phone: '09918141277',
		email: CREDENTIALS.SANTIAGOS,
		code: 'SXSJ',
		roles: [ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'Derly Silva',
		identification_card: '0000000008',
		phone: '0000000008',
		email: CREDENTIALS.DERLYS,
		code: 'DS',
		roles: [ROLES.TECHNICAL_ANALYST],
	},
	{
		full_name: 'Andres Ordonez',
		identification_card: '0000000008',
		phone: '0000000008',
		email: CREDENTIALS.ANDRESO,
		code: 'AO',
		roles: [ROLES.TECHNICAL_ANALYST],
	},
]
