export const GENERAL_ADMIN = 'general_admin'
export const DIRECTOR = 'director'
export const SUPERVISOR = 'supervisor'
export const TECHNICAL_ANALYST = 'analyst'
export const ACCESS_MANAGER = 'access_manager'
