export const REACTIVE_UNIT = {
	MASA: {
		GRAMO: 'g',
		MILIGRAMO: 'mg',
		KILOGRAMO: 'kg',
		TONELADA: 't',
		MICROGRAMO: 'µg',
		CENTIGRAMO: 'cg',
		DECAGRAMO: 'dag',
		ONZA: 'oz',
		LIBRA: 'lb',
	},
	VOLUMEN: {
		LITRO: 'l',
		MILILITRO: 'ml',
		GALON: 'gal',
		CENTIMETRO_CUBICO: 'cc',
		PINTA: 'pt',
		METRO_CUBICO: 'm3',
	},
	TEMPERATURA: {
		CELSIUS: '°C',
		FAHRENHEIT: '°F',
		KELVIN: 'K',
	},
	CONCENTRACION: {
		MOLARIDAD: 'M',
		NORMALIDAD: 'N',
		PORCENTAJE: '%',
	},
	UNIDADES: 'unit',
	AMPOLLAS: 'amp',
	PRUEBAS: 'pruebas',
	CORRIDAS: 'corridas',
	PETRIFILMS: 'petrifilms',
}
